### ISSUE TITLE
Can't Push Sketch

### ISSUE THREAD

**Issue by davidbitton** [bitflipser/ASMboot#2]
I have a non-Arduino 328p board. I was able to push ASMboot via USBasp with following command:
```
avrdude -v -v -c usbasp -p m328p -Uflash:w:ASMboot_328_16.hex:i
```

however when I use the Arduino IDE to push a Sketch, I get the dreaded `avrdude: stk500_getsync() ... ` error. I am able to push the optiboot boot loader and load a sketch, but the problem there is that I can only push a sketch once, and then I get the not in sync errors. Thanks.

**Comment by bitflipser** [comment]
At what speed is your board running?
Are you using the right USART-speed of 115.200 baud?

**Comment by davidbitton** [comment]
I found that my FTDI adapter may have been to blame. I used a different adapter, and now I can push a second sketch. From what I read, I wasn't getting the initial reset sent to the 328p. I have the optiboot on there and now. I'll go back and try ASMboot again.
